#index:
#    path: /
#    controller: App\Controller\DefaultController::index

fos_oauth_server_token:
  resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"
  options:
    expose: true

fos_oauth_server_authorize:
  resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

rest_api:
  type: rest
  resource: rest.yaml
  prefix: /api

