fos_rest:
#  body_listener: true
#  serializer:
#    serialize_null: true
  format_listener:
    rules:
      - { path: '^/api', priorities: ['json'], fallback_format: json, prefer_extension: false }
      - { path: '^/', priorities: ['html', '*/*'], fallback_format: html, prefer_extension: true }
#  param_fetcher_listener: true
  view:
    view_response_listener: true
#    formats:
#      json: true
      #html: true
#  exception:
#    enabled: true
#    messages:
#      Symfony\Component\HttpKernel\Exception\BadRequestHttpException: true
#      Symfony\Component\HttpKernel\Exception\NotFoundHttpException: true
#      Symfony\Component\HttpKernel\Exception\TooManyRequestsHttpException: true
#      Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: true

  routing_loader:
    default_format: json
    include_format: false
#  versioning: true
